window.DASHBOARD_CONFIG = {
  supabaseUrl: "https://YOUR-PROJECT.supabase.co",
  supabaseAnonKey: "YOUR_SUPABASE_ANON_KEY",
  appStatusKey: "main",
  historyLimit: 80,
  tables: {
    buySignals: "buy_signals",
    sellSignals: "sell_signals",
    risingSectorRows: "rising_sector_rows",
    earlyDetectionRows: "early_detection_rows",
    focusedWatchlistState: "focused_watchlist_state",
    candidatePromotions: "candidate_promotions",
    candidateDemotions: "candidate_demotions",
    tradeHistory: "trade_history",
    appStatus: "app_status",
    signalSettings: "signal_settings",
    signalPresets: "signal_presets",
    validationEvents: "validation_events",
    runtimeDiagnostics: "runtime_diagnostics",
    sessionReports: "session_reports",
    lastMarket: "rising_stocks_last_market",
  },
};
